# Generated by Django 4.1 on 2022-08-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poast',
            new_name='Post',
        ),
    ]
