# Generated by Django 4.1 on 2022-08-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_poast_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titile',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=1000000),
        ),
    ]
